version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8081:8081"
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: production

  client:
    build: ./client
    ports:
      - "3031:3031"
    volumes:
      - ./client:/usr/src/app
    environment:
      NODE_ENV: production
    depends_on:
      - server
