version: '3.8'

services:
  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - postgres-test
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_NAME
      - DB_PORT=$POSTGRESDB_DOCKER_PORT

  client:
    build: ./client
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    env_file:
      - ./client/.env

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_NAME
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ./server/db/postgres:/var/lib/postgresql/data
    env_file:
      - ./server/.env
  
  postgres-test:
    image: postgres:14
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_NAME
    ports:
      - $POSTGRESDB_TEST_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - ./server/db/test-db/postgres:/var/lib/postgresql/data
    env_file:
      - ./server/.env

volumes:
  postgres_data: