services:
  test-db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "2345:5432"
    volumes:
      - ./db/test:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  pgdata: